#「spring」の設定
spring:
  application:
    name: api
  #`.env` ファイルの読み込み
  config:
    import: optional:file:.env[.properties]
  # `.env` ファイルに定義した DB（MySQL）の設定を充てる
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    properties:
      mail:
        smtp:
          auth: ${MAIL_AUTH}
          starttls:
            enable: ${MAIL_ENABLE}
app:
  reset-url: ${RESET_URL}
  secret-code-expiration-time-min: ${SECRET_CODE_EXPIRATION_TIME_MIN}

#「JWT」の設定
jwt:
  # `.env` ファイルに定義した JWT_SECRET_KEY の設定を充てる
  secret: ${JWT_SECRET_KEY}

#「シークレットコード」の設定
secret-code:
  # `.env` ファイルに定義した SECRET_CODE_EXPIRATION_TIME_MIN の設定を充てる
  expiration-time: ${SECRET_CODE_EXPIRATION_TIME_MIN}