#　web開発用dockerFile

FROM node:20

# 必要なパッケージをインストール（lsof 用）
RUN apt-get update && apt-get install -y lsof && rm -rf /var/lib/apt/lists/*

#コンテナ内に　/workspace　を作り、以降の作業ディレクトリを　/workspace　にする
WORKDIR /workspace

COPY package*.json ./
RUN npm install

#カレントのデータ一式を　/workspace　にコピーする
COPY . .

CMD ["npm", "run", "dev"]